name: Build and test SQRL Functions
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: 'America/Los_Angeles'
    steps:
    - name: Setup Timezone
      uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "America/Los_Angeles"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull datasqrl/cmd Docker image
      run: docker pull datasqrl/cmd:latest

    - name: Run SQRL Math Test
      working-directory: ./sqrl-math
      run: |
        docker run -i --rm -v $PWD:/build datasqrl/cmd:latest test math.sqrl --snapshot snapshots-math
      continue-on-error: false
